INSERT INTO SOLICITACAO(DATA, DESCRICAO, TIPO) VALUES ('15/02/2022', 'Entulhos', 'Tipo 1');
INSERT INTO SOLICITACAO(DATA, DESCRICAO, TIPO) VALUES ('15/02/2022', 'Sofá quebrado', 'Tipo 1');
INSERT INTO SOLICITACAO(DATA, DESCRICAO, TIPO) VALUES ('15/02/2022', 'Caixas de papelão', 'Tipo 1');
INSERT INTO SOLICITACAO(DATA, DESCRICAO, TIPO) VALUES ('15/02/2022', 'Latinhas de cerveja', 'Tipo 1');
INSERT INTO SOLICITACAO(DATA, DESCRICAO, TIPO) VALUES ('15/02/2022', 'Entulhos', 'Tipo 1');
INSERT INTO SOLICITACAO(DATA, DESCRICAO, TIPO) VALUES ('15/02/2022', 'Guarda roupa velho', 'Tipo 3');
INSERT INTO SOLICITACAO(DATA, DESCRICAO, TIPO) VALUES ('15/02/2022', 'Entulhos', 'Tipo 4');
INSERT INTO SOLICITACAO(DATA, DESCRICAO, TIPO) VALUES ('15/02/2022', 'Entulhos', 'Tipo 5');
